spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/graphql
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update


server:
  port: '9001'
